#!/bin/sh
# alias j='z'
# alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'
# Paths
alias lv="cd $HOME/.local/share/lunarvim/lvim/lua/lvim"
alias m="cd $HOME/projects/mono"
alias live="cd $HOME/projects/mono-live"
alias z="cd $HOME/.config/zsh/"
alias p="cd $HOME/.local/share/lunarvim/site/pack/packer/start"
alias d="cd /var/lib/docker/volumes/lunarvim-docker_config/_data"
alias ut="source $HOME/projects/bash_scripts/login.sh"

# some stuff to allow remote connections from hosts on the network
alias startxrdp="sudo /etc/init.d/dbus start && sudo /etc/init.d/xrdp start"
alias pbcopy='clip.exe'
alias pbpaste="powershell.exe -command 'Get-Clipboard' | tr -d '\r' | head -n -1"

# Git
alias lg='lazygit'
alias ga="git add ."
alias gp="git pull"
# alias gs="git status"
alias gl="git log"

# Cloud Stuff
alias k="kubectl"
alias tc="telepresence connect"
alias login="export BROWSER=wslview && aws --profile development sso login"
alias login_prod="export BROWSER=wslview && aws --profile production sso login"
alias kcc="kubectl config current-context"
alias kl="kubectl logs"
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias sctl="systemctl"
alias jctl="journalctl"
alias find_services="systemctl list-units --type=service"
alias bdl="docker build -t lunarvim:latest ."
alias login_bb="/mnt/c/Windows/System32/OpenSSH/ssh.exe wpc-0083u"
alias login_ls="/mnt/c/Windows/System32/OpenSSH/ssh.exe buildbox03"
alias switch_to_prod="kubectl config use-context arn:aws:eks:ap-southeast-2:164522539201:cluster/nightlife-production-eks-cluster;"
alias switch_to_dev="kubectl config use-context arn:aws:eks:ap-southeast-2:174155838907:cluster/nightlife-development-eks-cluster;"
alias tell_me_contexts="kubectl config get-contexts;"
alias lvim_exec="$HOME/dotfiles/lvim_exec.sh"
alias lvim_docker="$HOME/dotfiles/lvim_docker.sh"

# Custom scripts
alias nt="bash addTabInTmux.sh"
alias ll="bash launchLogger.sh"
alias gs="bash generateAndSchemify.sh"
alias bd="bash buildAndDeploy.sh"
alias envFile="bash createEnvFiles.sh"
alias ld="bash launchDockerLvim.sh"

# The basics
alias t="tmux"
alias l="ls -a"
alias n="node"
alias c="clear"
alias v="lvim"
alias python=/usr/bin/python3.10

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
# alias remarkable_ssh='ssh root@10.11.99.1'
# alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
# alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
# alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

# alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

# alias m="git checkout master"
# alias s="git checkout stable"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
